services:
  app:
    container_name: app
    environment:
      DB_HOST: postgres
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "16000:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    hostname: postgres

    image: postgres:14.1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./scripts/postgres:/scripts
    ports:
      - "65432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: no

  db_backups:
    container_name: DB_Backups
    image: prodrigestivill/postgres-backup-local
    restart: always
    user: postgres:postgres
    volumes:
      - ./backups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      SCHEDULE: "@every 12h0m00s"
      BACKUP_KEEP_DAYS: 7
      HEALTHCHECK_PORT: 81
